// Writes src/version.ts from package.json so the injected runtime always
// reports its real version (no more hand-synced VERSION drift). Runs on
// prebuild; the generated file is committed so typecheck works standalone.
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const pkg = JSON.parse(readFileSync(join(here, '../package.json'), 'utf8'));
const out = join(here, '../src/version.ts');
const body = `// AUTO-GENERATED by scripts/gen-version.mjs — do not edit by hand.\n// Sourced from package.json at build time so the runtime reports its real version.\nexport const VERSION = '${pkg.version}';\n`;
writeFileSync(out, body, 'utf8');
